spring.application.name=Baitap8-Quest1

# Cấu hình Cổng Tomcat Server
server.port=8080

# Cấu hình H2 Database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Cấu hình Upload File
storage.location=uploads

# Cấu hình Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=false
springdoc.swagger-ui.disable-swagger-default-url=true